### ISSUE TITLE
require 'uriparser/uri_gem' not overriding URI.parse properly

### ISSUE THREAD

**Issue by jrochkind** [tlewin/ruby-uriparser#1]
Here:

https://github.com/tlewin/ruby-uriparser/blob/4bd4d5e8c7f152913f562c4ecf2637afaad4dd11/lib/uriparser/uri_gem.rb#L6

I think you mean to patch `self.parse` not `self.parser`, right?

**Comment by jrochkind** [comment]
However, this may not be a good idea to patch anyway. URIParser isn't necessarily swappable compatible with stdlib URI, when I try patching like this some things fail. 

I am intersted in the concept, running into performance problems with URI.parse, found this googling. 

I know it's very old code that doesn't seem to be maintained, curious if anyone is around with opinions on it.

**Comment by tlewin** [comment]
Hi,

Sorry for the delay to reply, I've been very busy recently.

Anyway, thanks for reaching out. I wrote the core of this library in a single night and I never had a chance to test in many different scenarios. At the time, I was improving the performance of a simple web API written in Goliath.

It's a long time that I don't work with ruby, so I am not following closely all the recent developments, but the idea was to have a drop in replacement for the default uri parser, so it would make easier for people to adopt it.

To be honest, I don't know if this still feasible nowadays, but I can do some research and patch the library.

By the way, you're right! The right name is `parse`. Thanks, I'll patch it.
